name: alarm_example
description: Demonstrates how to use the alarm plugin.
version: 0.1.2

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alarm: ^3.1.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3